[build]
  command = "ng build"
  publish = "dist/curso-angular-portifolio/browser"
 
[build.environment]
  NODE_VERSION = "20"

  [[redirects]]
  from = "/api/*"
  to = "https://pokeapi.co/:splat"
  status = 200
  force = true